import {
    defineStore
} from "pinia";

export const useNewsStore = defineStore('newsStore', {
    state: () => ({
        news: {
            items: [{
                    id: 1,
                    title: 'Top 5 Emerging Trends in the Software Development Industry',
                    imgSrc: 'src/assets/images/news/software-development.jpeg',
                    description: 'As the world becomes increasingly digital, the software development industry is experiencing rapid growth and evolution.',
                    user: 'Admin',
                    date: '22.12.2021',
                    informations: [
                        {
                            id: 1,
                            title: 'Low-code/No-code platforms',
                            description: 'One of the biggest emerging trends in software development is the rise of low-code/no-code platforms. These platforms allow developers to create software applications with minimal coding, instead using graphical interfaces and drag-and-drop tools. This is making software development more accessible to non-technical users and allowing businesses to develop applications faster and more efficiently.',
                        },
                        {
                            id: 2,
                            title: 'Artificial intelligence and machine learning',
                            description: 'Artificial intelligence and machine learning are becoming increasingly important in software development. These technologies are being used to develop more intelligent applications, automate tasks, and improve decision-making processes. As AI and ML continue to evolve, they are expected to play an even greater role in the software development industry.',
                        },
                        {
                            id: 3,
                            title: 'Cloud computing',
                            description: 'Cloud computing is already widely used in software development, but it continues to be an emerging trend. Cloud computing allows developers to easily access and use resources such as servers, storage, and databases without having to manage them on-premises. This makes it easier and more cost-effective for businesses to develop and deploy software applications',
                        },
                        {
                            id: 4,
                            title: 'Agile development methodologies',
                            description: 'Agile development methodologies are becoming increasingly popular in software development. These methodologies emphasize collaboration, flexibility, and continuous improvement. Agile methodologies are helping teams to deliver software applications faster and more efficiently, while also improving the quality of the software they produce.',
                        },
                        {
                            id: 5,
                            title: 'Internet of Things (IoT)',
                            description: 'The Internet of Things is an emerging trend that is having a big impact on software development. IoT devices are becoming more prevalent, and software developers are working to create applications that can interact with these devices. This is leading to the development of new software solutions and applications that are capable of processing and analyzing large amounts of data generated by IoT devices.',
                        }
                    ],
                    socialMedia: [
                        {
                            id: 1,
                            title: 'Facebook',
                            link: 'https://facebook.com',
                            icon: 'fa-brands fa-facebook-f'
                        },
                        {
                            id: 2,
                            title: 'LinkedIn',
                            link: 'https://linkedin.com',
                            icon: 'fa-brands fa-linkedin-in',
                        },
                        {
                            id: 3,
                            title: 'WhatsApp',
                            link: 'https://whatsapp.com',
                            icon: 'fa-brands fa-whatsapp'
                        }
                    ]
                },
                {
                    id: 2,
                    title: 'Our Company Wins Award for Innovation in Software Development',
                    imgSrc: 'src/assets/images/news/won-award.jpeg',
                    description: 'We are proud to announce that our company has been recognized for our innovation in software development. ',
                    user: 'Admin',
                    date: '22.12.2021',
                    informations: [
                        {
                            id: 1,
                            title: '',
                            description: 'Restly is thrilled to announce that we have won for Innovation in Software Development. This prestigious award is a testament to our commitment to innovation and excellence in the software development industry.'
                        },
                        {
                            id: 2,
                            title: '',
                            description: 'The Award recognizes companies that have demonstrated exceptional innovation in the development of software solutions. It acknowledges the ability to use technology to create unique and effective solutions that meet the ever-changing needs of the market.'
                        },
                        {
                            id: 3,
                            title: '',
                            description: 'At Restly, we are dedicated to staying ahead of the curve when it comes to software development. We invest heavily in research and development, and we work tirelessly to find new and innovative ways to solve problems and create software solutions that are tailored to the needs of our clients.'
                        },
                        {
                            id: 4,
                            title: '',
                            description: 'This award is a testament to the hard work and dedication of our talented team of developers, designers, and engineers. Their expertise and commitment to excellence are what make us stand out in a crowded industry.'
                        },
                        {
                            id: 5,
                            title: '',
                            description: 'We are thrilled to have been recognized for our achievements in software development, and we will continue to innovate and push the boundaries of what is possible in the years to come. We would like to thank the judges of the [Name of Award] for this incredible honor, and we look forward to continuing to deliver exceptional software solutions to our clients.'
                        }
                    ],
                    socialMedia: [
                        {
                            id: 1,
                            title: 'Facebook',
                            link: 'https://facebook.com',
                            icon: 'fa-brands fa-facebook-f'
                        },
                        {
                            id: 2,
                            title: 'LinkedIn',
                            link: 'https://linkedin.com',
                            icon: 'fa-brands fa-linkedin-in',
                        },
                        {
                            id: 3,
                            title: 'WhatsApp',
                            link: 'https://whatsapp.com',
                            icon: 'fa-brands fa-whatsapp'
                        }
                    ]
                },
                {
                    id: 3,
                    title: 'Introducing our latest product update: X version 2.0',
                    imgSrc: 'src/assets/images/news/product-update.jpeg',
                    description: 'We are excited to announce the release of X version 2.0 - our latest product update that brings a host of new features and improvements to our software.',
                    user: 'Admin',
                    date: '22.12.2021',
                    informations: [
                        {
                            id: 1,
                            title: 'Feature 1',
                            description: 'We\'ve added a powerful new feature that allows users to [insert description]. This will make it easier than ever before to [insert benefit].'
                        },
                        {
                            id: 2,
                            title: 'Feature 2',
                            description: 'We\'ve made significant improvements to [insert feature], which will help users to [insert benefit]. This will help to streamline workflows and increase productivity'
                        },
                        {
                            id: 3,
                            title: 'Feature 3',
                            description: 'We\'ve updated the user interface to make it more intuitive and user-friendly. This will make it easier for new users to get up and running with the product, while also providing more advanced users with the tools they need to get their work done quickly and efficiently'
                        }

                    ],
                    socialMedia: [
                        {
                            id: 1,
                            title: 'Facebook',
                            link: 'https://facebook.com',
                            icon: 'fa-brands fa-facebook-f'
                        },
                        {
                            id: 2,
                            title: 'LinkedIn',
                            link: 'https://linkedin.com',
                            icon: 'fa-brands fa-linkedin-in',
                        },
                        {
                            id: 3,
                            title: 'WhatsApp',
                            link: 'https://whatsapp.com',
                            icon: 'fa-brands fa-whatsapp'
                        }
                    ]
                },
            ],
            categories: [{
                    id: 1,
                    title: 'Business Strategy',
                    qty: 10,
                },
                {
                    id: 2,
                    title: 'Investment Planning',
                    qty: 5,
                },
                {
                    id: 3,
                    title: 'Financial Investment',
                    qty: 3
                },
                {
                    id: 4,
                    title: 'Software Development',
                    qty: 30,
                },
                {
                    id: 5,
                    title: 'Team Benefits',
                    qty: 10
                }
            ]
        },
    })
});